Novel Choices/app/database/models.py
from datetime import datetime
from app import db
    
class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    date_of_creation = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    reviewer_id = db.Column(db.String(64), index=True, unique=True, default=None)
    reviewer_name = db.Column(db.String(64), index=True)
    email = db.Column(db.String(64), index=True, unique=True, default=None)
    password = db.Column(db.String(64), index=True, default=None)
    
    def __repr__(self):
        return '<User\nName={}\nDate of Creation={}\Reviewer ID={}'.format(self.reviewer_name, self.date_of_creation, self.reviewer_id)

def load_user(id):
    return User.query.get(int(id))

class Book(db.Model):
    __tablename__ = 'books'
    id = db.Column(db.Integer, primary_key=True)
    date_of_creation = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    asin = db.Column(db.String(32), index=True)
    title = db.Column(db.String(128), index=True)
    price = db.Column(db.String(32), index=True, default=None)
    imUrl = db.Column(db.String(128), index=True, default=None)
    description = db.Column(db.String(1024), default=None)
    sales_rank = db.Column(db.String(32), index=True, default=None)
    also_bought = db.Column(db.String(32), default=None)
    also_viewed = db.Column(db.String(32), default=None)
    bought_together = db.Column(db.String(32), default=None)
    buy_after_viewing = db.Column(db.String(32), default=None)

    def __repr__(self):
        return '<Book\nBook ID={}\nTitle={}\ASIN={}>'.format(self.id, self.title, self.asin)

def load_book(id):
    return Book.query.get(int(id))

class Rating(db.Model):
    __tablename__ = 'ratings'
    id = db.Column(db.Integer, primary_key=True)
    date_of_creation = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    overall = db.Column(db.Integer, index=True)
    book_id = db.Column(db.Integer, db.ForeignKey('books.id'), index=True)
    
    # use this for now until user registration is implemented
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), index=True, default=None)

    # TODO:implement user registration so we dont
    # have to keep null record of the user in the ratings table
    # user_id = db.Column(db.Integer, db.ForeignKey('users.id'), index=True)

    # Define relationship to user
    user = db.relationship('User', backref=db.backref('ratings', order_by=id))

    # Define relationship to book
    book = db.relationship('Book', backref=db.backref('ratings', order_by=id))

    def __repr__(self):
        return '<Rating\nRating ID={}\nRating={}\nBook ID={}\nuUser ID={}'.format(self.id, self.overall, self.book_id, self.user_id)

def load_rating(id):
    return Rating.query.get(int(id))

Novel Choices/app/rec_sys/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField

class SubmitForm(FlaskForm):
    submit = SubmitField('Get predictions')

Novel Choices/app/__init__.py
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os
from flask import Flask, request, current_app
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config


db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
    
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    migrate.init_app(app, db)

    with app.app_context():
        # Flask Routes
        from app.main import bp as main_bp
        app.register_blueprint(main_bp)
        from app.dashboard import bp as dashboard_bp
        app.register_blueprint(dashboard_bp)
        from app.report import bp as report_bp
        app.register_blueprint(report_bp)
        from app.rec_sys import bp as rec_sys_bp
        app.register_blueprint(rec_sys_bp)

        return app

Novel Choices/app/dashboard/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard', __name__, template_folder='templates')

from app.dashboard import routes

Novel Choices/app/dashboard/routes.py
from flask import render_template, flash, redirect, \
url_for, request, json
from werkzeug.urls import url_parse
from app import db
from app.dashboard import bp

@bp.route('/dashboard')
def dashboard():
    stats = []
    return render_template('dashboard.html', title='Big Data Algorithms Project', stats=stats)





"""
the dashbaoard will be composed from several handler functions
that each take care of rendering the graph on full 
html pages like in Dash. So the UI is made from a bunch of
rendered graphs, each having their own web pages.
On the UI we can postion and size them in the section tag
using iFrames.
"""


Novel Choices/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__, template_folder='templates')

from app.main import routes

Novel Choices/app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, jsonify, current_app
from app import db
from app.main import bp


# before request check if we're
# working with local storage
# if yes, check associated directories for seeded data
#   if exists, pass
#   else populate
# else setup cloud pipeline
@bp.route('/')
def main():
    return render_template('main.html', title='Big Data Algorithms Project')
              

Novel Choices/app/rec_sys/__init__.py
from flask import Blueprint

bp = Blueprint('rec_sys', __name__, template_folder='templates')

from app.rec_sys import routes

Novel Choices/app/rec_sys/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, session
from app import db
from app.database.models import Book, User, Rating
from app.rec_sys import bp


def get_prediction(books, ratings):
    return Book.query.all()[:10]

@bp.route('/rec_sys', methods=['GET', 'POST'])
def rec_sys():

    books = Book.query.all()[:10]

    if request.method == 'POST':
        keys = [key for key in request.form.keys()]
        ratings = []
        for i in range(5):
            ratings.append(request.form[keys[i]])
            db.session.add(
                Rating(
                    overall=ratings[i],
                    book_id=books[i].id,
                    user_id=0
                )
            )
        db.session.commit()
        session['books'] = {
            'book0': books[0].asin,
            'book1': books[1].asin,
            'book2': books[2].asin,
            'book3': books[3].asin,
            'book4': books[4].asin

        }
        session['ratings'] = {
            'rating0': ratings[0],
            'rating1': ratings[1],
            'rating2': ratings[2],
            'rating3': ratings[3],
            'rating4': ratings[4]
        }

    return render_template('rec_sys.html',title='Big Data Algorithms Project',books=books)

@bp.route('/prediction')
def prediction():
    print(session['ratings'])

    results = get_prediction(None,None)
    return render_template('results.html',title='Big Data Algorithms Project', results=results)
    
@bp.route('/book/<asin>')
def book(asin):
    return render_template(
        'book.html',
        title='Big Data Algorithms Project',
        book=Book.query.filter_by(asin=asin).all()[0]
    )

Novel Choices/app/report/__init__.py
from flask import Blueprint

bp = Blueprint('report', __name__, template_folder='templates')

from app.report import routes

Novel Choices/app/report/routes.py
from flask import render_template, flash, redirect, \
url_for, request
from werkzeug.urls import url_parse
from app import db
from app.report import bp

@bp.route('/report')
def report():
    return render_template('report.html', title='Big Data Algorithms Project')

Novel Choices/app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='dashboard.css') }}">
    <title>Dashboard</title>
</head>d

<body>

    <div class='dashboard'>
        <header>
            <nav id="main-nav">
                <a href="{{ url_for('main.main') }}">Home</a>
                <a href="#">Dashboard</a>
                <a href="{{ url_for('report.report') }}">Report</a>
                <a href="{{ url_for('rec_sys.rec_sys') }}">Recommendation</a>
            </nav>
            <nav id='dash-nav'>
                <a href="#">2018</a>
                <a href="#">Charts</a>
                <a href="#">Data</a>
                <a href="#">Info</a>
            </nav>
        </header>

        <main>
            <section class="page page-title">
                <div class="title-content">
                    <h2>2020 Amazon Book Benchmark</h2>
                    <p>This report describes Amazon's Book Review Dataset results</p>
                </div>
            </section>

            <section class='page page-chart'>
                <div class="chart-content">
                    <h2>Stats By Book Type</h2>

                    <h3>Top Reviews by Negative Review</h3>
                    <p>Normal Histogram</p>
                    <div class="chart">
                        <iframe src="http://127.0.0.1:8050/" frameborder="0">
                            Chart Goes Here
                        </iframe>
                    </div>
                </div>
            </section>

            <section class='page page-stat'>
                <div class="stat-content">
                    <h2 id='stat_1' class="stat">0</h2>
                    <!-- <h2 id='stat_1_val' hidden>{{ stats[0] }}</h2> -->
                    <p>2020's median Ranking for each Genre. The national median is 50.</p>
                </div>
            </section>

            <section class='page page-chart'>
                <div class="chart-content">
                    <h2> Year Published & Price Breakdown</h2>

                    <h3>Horizontal Bar Chart</h3>
                    <p>Most Frequently used words in complaints</p>
                    <div class="chart">
                        <iframe src="http://127.0.0.1:8050/" frameborder="0">
                          Chart Goes Here
                        </iframe>
                    </div>
                </div>
            </section>

            <section class='page page-stat'>
                <div class="stat-content">
                    <h2 id='stat_2' class="stat">0</h2>
                    <!-- <h2 id='stat_2_val' hidden>{{ stats[1] }}</h2> -->

                    <p>Lorizzle ipsizzle dolor fo shizzle, shizzlin dizzle adipiscing shizznit.</p>
                </div>
            </section>

            <section class='page page-chart'>
                <div class="chart-content">
                    <h2>Comparison</h2>
                    <p>Treemap</p>
                    <p>Wordcloud</p>
                    <div class="chart">
                        <iframe src="http://127.0.0.1:8050/" frameborder="0">
                            Chart Goes Here
                        </iframe>
                    </div>
                </div>
            </section>

            <section class='page page-stat'>
                <div class="stat-content">
                    <h2 id='stat_3' class="stat">0</h2>
                    <!-- <h2 id='stat_3_val' hidden>{{ stats[2] }}</h2> -->

                    <p>Lorizzle ipsizzle dolor fo shizzle, shizzlin dizzle adipiscing shizznit.</p>
                </div>
            </section>

            <section class='page page-chart'>
                <div class="chart-content">
                    <h2>Comparison</h2>
                    <p>Topic modelling using LDA</p>
                    <div class="chart">
                        <iframe src="http://127.0.0.1:8050/" frameborder="0">
                            Chart Goes Here
                        </iframe>
                    </div>
                </div>
            </section>

            <section class='page page-stat'>
                <div class="stat-content">
                    <h2 id='stat_4' class="stat">0</h2>
                    <!-- <h2 id='stat_4_val' hidden>{{ stats[3] }}</h2> -->

                    <p>Topic modelling using LDA</p>
                </div>
            </section>
        </main>
        <footer>
            <div id="credits" class="footer-detail">
                <h4>Credits</h4>
                <p>This tool was developed by<a href="https://www.instagram.com/ultra_devin/"> Devin Custodio </a>for the Rutgers University-Camden Big Data Algorithms Course.</p>
            </div>
            <br>
            <div id="contact" class="footer-detail">
                <h4>Contact</h4>

                <p>Questions about the tool, the data, or the energy benchmarking program can be directed to Devin at <a href="mailto: devin.roy.custodio@gmail.com">devin.roy.custodio@gmail.com.</a></p>
            </div>
            <br>
            <div id="full-report" class="footer-detail">
                <h4>Full Report</h4>
                <p>For more information and to see the full report, please visit the results site <a href="{{ url_for('report.report') }}">here</a>.</p>
            </div>
        </footer>
        <div id="glossary"></div>
    </div>




    <script src="{{ url_for('static', filename='countUp.js') }}"></script>

    <script>
        window.onload = function() {
            var stat1_val = parseInt(document.getElementById('stat_1_val').innerHTML);
            var stat2_val = parseInt(document.getElementById('stat_2_val').innerHTML);
            var stat3_val = parseInt(document.getElementById('stat_3_val').innerHTML);
            var stat4_val = parseInt(document.getElementById('stat_4_val').innerHTML);

            document.getElementById('stat_1_val').remove();
            document.getElementById('stat_2_val').remove();
            document.getElementById('stat_3_val').remove();
            document.getElementById('stat_4_val').remove();

            var stat1 = new CountUp('stat_1', stat1_val);
            var stat2 = new CountUp('stat_2', stat2_val);
            var stat3 = new CountUp('stat_3', stat3_val);
            var stat4 = new CountUp('stat_4', stat4_val);

            stat1.start();
            stat2.start();
            stat3.start();
            stat4.start();

        }
    </script>

</body>

</html>

Novel Choices/app/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../static/main.css">
</head>

<body>
    <!---------------------------------------------- BEGIN CONTAINER ------------------------------------->
    <div class="container">
        <!---------------------------------------------- BEGIN CARD 1 ------------------------------------->
        <div class="card">
            <div class="face face1 dashboard">
                <div class="content">
                    <img src="{{ url_for('static', filename='image/combo-chart.png') }}">
                </div>
            </div>


            <div class="face face2">
                <div class="content">
                    <p>Dashboard blah blah blah</p>
                    <a href="{{ url_for('dashboard.dashboard') }}">Read More</a>
                </div>
            </div>
        </div>
        <!---------------------------------------------- END CARD 1 ------------------------------------->


        <!---------------------------------------------- BEGIN CARD 2 ------------------------------------->
        <div class="card">
            <div class="face face1 report">
                <div class="content">
                    <img src="{{ url_for('static', filename='image/paper.png') }}">
                </div>
            </div>
            <div class="face face2">
                <div class="content">
                    <p>Report blah blah blah</p>
                    <a href="{{ url_for('report.report') }}">Read More</a>
                </div>
            </div>
        </div>
        <!---------------------------------------------- END CARD 2 ------------------------------------->


        <!---------------------------------------------- BEGIN CARD 3 ------------------------------------->
        <div class="card">
            <div class="face face1 recommendation">
                <div class="content">
                    <img src="{{ url_for('static', filename='image/list.png') }}">
                </div>
            </div>

            <div class="face face2">
                <div class="content">
                    <p>Recommendation blah blah blah</p>
                    <a href="{{ url_for('rec_sys.rec_sys') }}">Read More</a>
                </div>
            </div>
        </div>
        <!---------------------------------------------- END CARD 3 ------------------------------------->

    </div>
    <!---------------------------------------------- END CONTAINER ------------------------------------->

</body>

</html>

Novel Choices/app/templates/rec_sys.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='rec-sys.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <title>Ratings</title>

    <style>
        .stars-outer {
            position: relative;
            display: inline-block;
        }
        
        .stars-inner {
            position: absolute;
            top: 0;
            left: 0;
            white-space: nowrap;
            overflow: hidden;
            width: 0;
        }
        
        .stars-outer::before {
            content: "\f005 \f005 \f005 \f005 \f005";
            font-family: 'Font Awesome 5 Free';
            font-weight: 900;
            color: #ccc;
        }
        
        .stars-inner::before {
            content: "\f005 \f005 \f005 \f005 \f005";
            font-family: 'Font Awesome 5 Free';
            font-weight: 900;
            color: rgb(122, 216, 200);
        }
    </style>
</head>

<body>

    <header>
        <nav class="nav">
            <a href="{{ url_for('main.main') }}">Home</a>
            <a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a>
            <a href="{{ url_for('report.report') }}">Report</a>
            <a href="#">Recommendation</a>
        </nav>
        <nav class='white-space'>
        </nav>
    </header>
    <div class="Grid Grid--up "><span class="Grid__unit Grid__unit--spacer "></span></div>
    <h1 class="Heading ">Novel Choices is a recommendation resource showcasing totally amazing books.</h1>
    <div class="grid grid-down">
    <div class="container mt-5">
        <div class="form-group">
            <select id="book-select" class="form-control custom-select">
                <option value="0" disabled selected>Select Book</option>
                <option value="book0">{{ books[0].title }}</option>
                <option value="book1">{{ books[1].title }}</option>
                <option value="book2">{{ books[2].title }}</option>
                <option value="book3">{{ books[3].title }}</option>
                <option value="book4">{{ books[4].title }}</option>
                <option value="book5">{{ books[5].title }}</option>
                <option value="book6">{{ books[6].title }}</option>
                <option value="book7">{{ books[7].title }}</option>
                <option value="book8">{{ books[8].title }}</option>
                <option value="book9">{{ books[9].title }}</option>
            </select>
        </div>
        <div class="form-group">
            <input step='0.1' min='1' max='5' placeholder="rate 1 - 5" disabled type="number" id="rating-control" class="form-control">
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Book</th>
                    <th>Ratings</th>
                </tr>
            </thead>
            <tbody>
                <tr class="book0">
                    <td><a href="{{ url_for('rec_sys.book', asin=books[0].asin) }}">{{ books[0].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr>
                <tr class="book1">
                    <td><a href="{{ url_for('rec_sys.book', asin=books[1].asin) }}">{{ books[1].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr>
                <tr class="book2">
                    <td><a href="{{ url_for('rec_sys.book',asin=books[2].asin) }}">{{ books[2].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr>
                <tr class="book3">
                    <td><a href="{{ url_for('rec_sys.book',asin=books[3].asin) }}">{{ books[3].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr>
                <tr class="book4">
                    <td><a href="{{ url_for('rec_sys.book',asin=books[4].asin) }}">{{ books[4].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr>
                <tr class="book5">
                    <td><a href="{{ url_for('rec_sys.book', asin=books[5].asin) }}">{{ books[5].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr><tr class="book6">
                    <td><a href="{{ url_for('rec_sys.book', asin=books[6].asin) }}">{{ books[6].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr><tr class="book7">
                    <td><a href="{{ url_for('rec_sys.book', asin=books[7].asin) }}">{{ books[7].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr><tr class="book8">
                    <td><a href="{{ url_for('rec_sys.book', asin=books[8].asin) }}">{{ books[8].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr><tr class="book9">
                    <td><a href="{{ url_for('rec_sys.book', asin=books[9].asin) }}">{{ books[9].title }}</a></td>
                    <td>
                        <div class="stars-outer">
                            <div class="stars-inner"></div>
                        </div>
                        <span class="number-rating"></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="form-group">
        <button id="prediction-control" type="submit" disabled onclick="send_ratings();"><a id ='get-predictions' onclick="return false;" style="text-decoration: none; color: buttonText;" href="{{ url_for('rec_sys.prediction') }}">Get Prediction</a></button>
    </div>

    <script>
        function send_ratings() {
            rating_control.disabled = true;
            $.post("/rec_sys", {
                javascript_data: ratings
            });
        }
    </script>
    
    <script>
        // inital ratings
        const ratings = {
            book0: 1,
            book1: 1,
            book2: 1,
            book3: 1,
            book4: 1,
            book5: 1,
            book6: 1,
            book7: 1,
            book8: 1,
            book9: 1,
        };

        // max rating
        const total_stars = 5;

        // run get ratings when DOM loads
        document.addEventListener('DOMContentLoaded', getRatings);

        // form elements
        const book_select = document.getElementById('book-select');
        const rating_control = document.getElementById('rating-control');
        const prediction_control = document.getElementById('prediction-control');
        const get_predictions = document.getElementById('get-predictions');


        // init book
        let book;

        // book select change
        book_select.addEventListener('change', (e) => {
            book = e.target.value;
            // enable rating control
            rating_control.disabled = false;
            prediction_control.disabled = false;
            get_predictions.onclick = 'return true';
            rating_control.value = ratings[book]
        });

        // rating control change
        rating_control.addEventListener('blur', (e) => {
            const rating = e.target.value;
            // make sure 5 or under
            if (rating > 5 || rating < 1) {
                alert('Please rate 1 - 5');
                prediction_control.disabled = true;
                get_predictions.onclick = 'return false';
                return ;
            }
            // change the rating
            ratings[book] = rating;
            getRatings();
        });

        // get ratings
        function getRatings() {
            for (let rating in ratings) {
                // get percentage
                const starPercentage = (ratings[rating] / total_stars) * 100;

                // round to nearest 10
                const startPercentageRounded = `${Math.round(starPercentage / 10) * 10}%`;

                // set width of stars-inner to percentage
                document.querySelector(`.${rating}
                .stars-inner`).style.width =
                    startPercentageRounded;

                // add number rating
                document.querySelector(`.${rating}
                .number-rating`).innerHTML = ratings[rating];
            }
        }
    </script>
</body>

Novel Choices/app/templates/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='rec-sys.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stars.css') }}">
    <title>Results</title>
</head>

<body>

    <div class='rec-sys'>
        <header>
            <nav class="nav">
                <a href="{{ url_for('main.main') }}">Home</a>
                <a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a>
                <a href="{{ url_for('report.report') }}">Report</a>
                <a href="{{ url_for('rec_sys.rec_sys') }}">Recommendation</a>
            </nav>
            <nav class='white-space'>
            </nav>
        </header>


        <main class='Main'>
            <div class="Grid Grid--up "><span class="Grid__unit Grid__unit--spacer "></span></div>
            <h1 class="Heading ">Thank you for using Novel Choices. Please enjoy your suggested content.</h1>
            <div class="grid grid-down">

                {% for result in results %}
                <div class="Grid__unit ">
                    <article class="Preview" data-year="2019" data-month="12">
                        <div class="Browser ">
                            <div class="Browser__chrome "><span class="Browser__dots "></span></div>
                            <div class="Browser__bd ">
                                <figure class="Preview__fig "><span style="padding-bottom:62.5%;background-color:rgb(155, 24, 122);" class="Imgset is-loaded"></span>
                                    <div class="Preview__actions ">
                                        <a href="https://amazon-asin.com/asincheck/?product_id={{ result.asin }}" target="_blank" class="Preview__action Preview__action--globe">
                                            <div class="Preview__actionText ">Visit Website</div>
                                        </a>
                                        <a href="{{ url_for('rec_sys.book',asin=result.asin) }}" class="Preview__action Preview__action--eye">
                                            <div class="Preview__actionText ">Details</div>
                                        </a>
                                    </div>
                                </figure>
                            </div>
                        </div>
                        <div class="Preview__meta ">
                            <h1 class="Preview__title ">{{ result.title }}</h1>
                        </div>
                    </article>
                </div>
                {% endfor %}
            </div>
        </main>
    </div>

</body>

</html>